[package]
name = "hexga_serde"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme = "README.md"

keywords = []
description = "Export common Serde serializers and deserializers in a unified way (json, ron, ...)"
categories = ["encoding", "data-structures"]

[dependencies]
hexga_encoding = { workspace = true, features = ["serde"] }
serde = { version = "1.0.0" }

ron = { version = "0.11.0" }
serde_json = { version = "1.0.133" }
serde-xml-rs = { version = "0.8.1" }
bincode = { version = "1.3.3" }
