[package]
name = "hexga_wgpu_graphics"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme = "README.md"

description = ""
keywords = ["multimedia", "graphics"]
categories = ["game-development", "graphics"]

[features]
default = [
            "int_are_32_bits", "float_are_32_bits",
            "serde", "serde_rc", "hexga_encoding_derive",
            "webgpu"
          ]

int_are_8_bits    = ["hexga/int_are_8_bits", "hexga_graphics/int_are_8_bits", "hexga_wgpu/int_are_8_bits"]
int_are_16_bits   = ["hexga/int_are_16_bits", "hexga_graphics/int_are_16_bits", "hexga_wgpu/int_are_16_bits"]
int_are_32_bits   = ["hexga/int_are_32_bits", "hexga_graphics/int_are_32_bits", "hexga_wgpu/int_are_32_bits"]
int_are_64_bits   = ["hexga/int_are_64_bits", "hexga_graphics/int_are_64_bits", "hexga_wgpu/int_are_64_bits"]
int_are_size_bits = ["hexga/int_are_size_bits", "hexga_graphics/int_are_size_bits", "hexga_wgpu/int_are_size_bits"]

float_are_32_bits   = ["hexga/float_are_32_bits", "hexga_graphics/float_are_32_bits", "hexga_wgpu/float_are_32_bits"]
float_are_64_bits   = ["hexga/float_are_64_bits", "hexga_graphics/float_are_64_bits", "hexga_wgpu/float_are_64_bits"]
float_are_size_bits = ["hexga/float_are_size_bits", "hexga_graphics/float_are_size_bits", "hexga_wgpu/float_are_size_bits"]

serde = ["dep:serde", "hexga/serde", "hexga_graphics/serde", "hexga_wgpu/serde"]
serde_rc = ["serde/rc", "hexga/serde_rc", "hexga_graphics/serde_rc", "hexga_wgpu/serde_rc"]

hexga_encoding_derive = ["hexga/hexga_encoding_derive", "hexga_graphics/hexga_encoding_derive", "hexga_wgpu/hexga_encoding_derive"]

webgpu = ["hexga_wgpu/webgpu"]

[dependencies]
hexga.workspace = true
hexga_wgpu.workspace = true
hexga_graphics.workspace = true
serde = { version = "1.0.0", features = ["derive"], optional = true }

